
### --------------------------------------------------------------------
POST http://57.129.22.122:4001/api/auth/login
Content-Type: application/json

{
  "email": "dev@user.com",
  "password": "DevPass123!"
}

### --------------------------------------------------------------------
GET http://57.129.22.122:4001/api/device
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2MGFmODk4OS1iYmZkLTRlZjYtOWNiMy1hYjAwOTY3ZmNkMTUiLCJpZCI6IjEiLCJlbWFpbCI6ImRldkB1c2VyLmNvbSIsIm9yZ19pZCI6IjEiLCJ0b2tlbl92ZXJzaW9uIjoyMywiaWF0IjoxNzU1ODQ3MzI5LCJleHAiOjE3NTU4OTA1Mjl9.GvGVfyDqL9YG5IXfay-tzNMEb-D2YieWMBrS-lLICQA

### --------------------------------------------------------------------
PATCH  http://57.129.22.122:4001/api/device/1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2MGFmODk4OS1iYmZkLTRlZjYtOWNiMy1hYjAwOTY3ZmNkMTUiLCJpZCI6IjEiLCJlbWFpbCI6ImRldkB1c2VyLmNvbSIsIm9yZ19pZCI6IjEiLCJ0b2tlbl92ZXJzaW9uIjoyMywiaWF0IjoxNzU1ODQ3MzI5LCJleHAiOjE3NTU4OTA1Mjl9.GvGVfyDqL9YG5IXfay-tzNMEb-D2YieWMBrS-lLICQA

{
   "external_id_type": "imeie"
}

### --------------------------------------------------------------------

DELETE http://57.129.22.122:4001/api/device
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2MGFmODk4OS1iYmZkLTRlZjYtOWNiMy1hYjAwOTY3ZmNkMTUiLCJpZCI6IjEiLCJlbWFpbCI6ImRldkB1c2VyLmNvbSIsIm9yZ19pZCI6IjEiLCJ0b2tlbl92ZXJzaW9uIjoyMywiaWF0IjoxNzU1ODQ3MzI5LCJleHAiOjE3NTU4OTA1Mjl9.GvGVfyDqL9YG5IXfay-tzNMEb-D2YieWMBrS-lLICQA

{
  "device_ids": ["64"]
}

### --------------------------------------------------------------------

POST http://57.129.22.122:4001/api/device
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2MGFmODk4OS1iYmZkLTRlZjYtOWNiMy1hYjAwOTY3ZmNkMTUiLCJpZCI6IjEiLCJlbWFpbCI6ImRldkB1c2VyLmNvbSIsIm9yZ19pZCI6IjEiLCJ0b2tlbl92ZXJzaW9uIjoyMywiaWF0IjoxNzU1ODQ3MzI5LCJleHAiOjE3NTU4OTA1Mjl9.GvGVfyDqL9YG5IXfay-tzNMEb-D2YieWMBrS-lLICQA

{
  "organisation_id": "6",   
  "asset_id" : "1",       
  "external_id": "3338",
  "external_id_type": "imei",
  "protocol": "udp",
  "vendor": "teltonika",
  "model": "FMC130",
  "status": "active",
  "attributes": {
    "color": "black",
    "version": "1.0"
  }
}

### --------------------------------------------------------------------