### --------------------------------------------------------------------
GET http://57.129.22.122:4001/api/device
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJmOGYyZGEzMy0xZDE2LTRlYjUtOGJiOS1mYTNlYmY5ZTdiOTkiLCJpZCI6IjIiLCJlbWFpbCI6ImFsaWNlQGFjbWUuY29tIiwicm9sZV9pZCI6Miwib3JnX2lkIjoiMSIsInRva2VuX3ZlcnNpb24iOjYyMSwiaWF0IjoxNzcyNTQ4NzEwLCJleHAiOjE3NzI1OTE5MTB9.1jWNlzDQ0HsXjYosn_IWVJebGQBk9GUJEf0r1vjV_fk

### --------------------------------------------------------------------
PATCH  http://57.129.22.122:4001/api/device/1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJmOGYyZGEzMy0xZDE2LTRlYjUtOGJiOS1mYTNlYmY5ZTdiOTkiLCJpZCI6IjIiLCJlbWFpbCI6ImFsaWNlQGFjbWUuY29tIiwicm9sZV9pZCI6Miwib3JnX2lkIjoiMSIsInRva2VuX3ZlcnNpb24iOjYyMSwiaWF0IjoxNzcyNTQ4NzEwLCJleHAiOjE3NzI1OTE5MTB9.1jWNlzDQ0HsXjYosn_IWVJebGQBk9GUJEf0r1vjV_fk

{
   "asset_id": "1"
}

### --------------------------------------------------------------------

DELETE http://57.129.22.122:4001/api/device
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJmOGYyZGEzMy0xZDE2LTRlYjUtOGJiOS1mYTNlYmY5ZTdiOTkiLCJpZCI6IjIiLCJlbWFpbCI6ImFsaWNlQGFjbWUuY29tIiwicm9sZV9pZCI6Miwib3JnX2lkIjoiMSIsInRva2VuX3ZlcnNpb24iOjYyMSwiaWF0IjoxNzcyNTQ4NzEwLCJleHAiOjE3NzI1OTE5MTB9.1jWNlzDQ0HsXjYosn_IWVJebGQBk9GUJEf0r1vjV_fk

{
  "device_ids": ["73"]
}

### --------------------------------------------------------------------

POST http://57.129.22.122:4001/api/device
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJmOGYyZGEzMy0xZDE2LTRlYjUtOGJiOS1mYTNlYmY5ZTdiOTkiLCJpZCI6IjIiLCJlbWFpbCI6ImFsaWNlQGFjbWUuY29tIiwicm9sZV9pZCI6Miwib3JnX2lkIjoiMSIsInRva2VuX3ZlcnNpb24iOjYyMSwiaWF0IjoxNzcyNTQ4NzEwLCJleHAiOjE3NzI1OTE5MTB9.1jWNlzDQ0HsXjYosn_IWVJebGQBk9GUJEf0r1vjV_fk

{
  "organisation_id": "2",   
  "asset_id" : "1",       
  "external_id": "3338",
  "external_id_type": "imei",
  "protocol": "udp",
  "vendor": "teltonika",
  "model": "FMC130",
  "status": "active",
  "attributes": {
    "color": "black",
    "version": "1.0"
  }
}