### --------------------------------------------------------------------
POST http://57.129.22.122:4001/api/group
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJmOGYyZGEzMy0xZDE2LTRlYjUtOGJiOS1mYTNlYmY5ZTdiOTkiLCJpZCI6IjIiLCJlbWFpbCI6ImFsaWNlQGFjbWUuY29tIiwicm9sZV9pZCI6Miwib3JnX2lkIjoiMSIsInRva2VuX3ZlcnNpb24iOjYyMCwiaWF0IjoxNzcwNTc3ODk4LCJleHAiOjE3NzA2MjEwOTh9.jZKbqknjRp2jMYiYrU7SZYhh_qlnp4p_LaU25PdOMGE

{
    "name" : "Test Org Groups",
    "type" : "organisation"
}

### --------------------------------------------------------------------
DELETE http://57.129.22.122:4001/api/group
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJmOGYyZGEzMy0xZDE2LTRlYjUtOGJiOS1mYTNlYmY5ZTdiOTkiLCJpZCI6IjIiLCJlbWFpbCI6ImFsaWNlQGFjbWUuY29tIiwicm9sZV9pZCI6Miwib3JnX2lkIjoiMSIsInRva2VuX3ZlcnNpb24iOjYyMCwiaWF0IjoxNzcwNTc3ODk4LCJleHAiOjE3NzA2MjEwOTh9.jZKbqknjRp2jMYiYrU7SZYhh_qlnp4p_LaU25PdOMGE

{
  "group_ids": ["3", "7"]
}

